### ISSUE TITLE
Error when convert Pdf file on linux

### ISSUE THREAD

**Issue by duduche59** [nathfavour/bionicpython#6]
hello,
I get the following error when I convert my pdf file: 
[INFO] Terminated in 11.31s.
Unexpected error processing document: local variable 'output_path' referenced before assignment

My config : linux mint 21.3
Python 3.10.12

how to correct this error ?

Thanks

**Comment by nathfavour** [comment]
Yeah, I noticed that too, sorry, i think it's from the last pull request.
Fixing soon.

**Comment by nathfavour** [comment]
ok, I just fixed the issue you can run 'git pull' now. Thanks

**Comment by duduche59** [comment]
Super. Work fine.
Very thanks.
